[package]
name = "mini-sisso"
version = "0.2.5"
edition = "2021"
exclude = ["target", ".venv", ".git", "dist", "*.ipynb", ".DS_Store", ".gitignore", "Cargo.lock", "uv.lock"]

[lib]
name = "_mini_sisso_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }
numpy = "0.23"
ndarray = { version = "0.15", features = ["rayon"] }
rayon = "1.10"
nalgebra = "0.32" # 純Rustの線形代数ライブラリ (BLAS不要)
itertools = "0.12"
